services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "9797:80"
        env_file:
            - .env
        depends_on:
            - db_stegadventure
        networks:
            - app-network

    db_stegadventure:
        image: mysql:8.0
        container_name: db_stegadventure
        restart: unless-stopped
        ports:
            - "9333:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
