user www-data;
worker_processes auto;
error_log /dev/stderr warn;
pid /run/nginx.pid;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile on; tcp_nopush on; tcp_nodelay on;
    keepalive_timeout 65;
    server_tokens off;

    gzip on; gzip_vary on; gzip_proxied any; gzip_comp_level 5;
    gzip_types text/plain text/css text/xml application/json application/javascript
               application/xml+rss application/atom+xml image/svg+xml;

    access_log /dev/stdout;

    server {
        listen 80 default_server;
        server_name _;
        root /var/www/public;
        index index.php index.html;
        client_max_body_size 25m;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location ~ /\.(?!well-known) { deny all; }
    }
}
