<template>
    <div ref="graphContainer" />
</template>

<script setup>
// This script is generated by ChatGPT
import { ref, onMounted } from "vue";
import * as d3 from "d3";

// Props for nodes and links
const props = defineProps({
    nodes: {
        type: Array,
        required: true,
    },
    links: {
        type: Array,
        required: true,
    },
});

const graphContainer = ref(null); // Reference to the container div

// Function to create the directed graph
function createGraph() {
    const width = window.innerWidth;
    const height = window.innerHeight;

    // Create the SVG container
    const svg = d3
        .select(graphContainer.value)
        .append("svg")
        .attr("width", "100vw")
        .attr("height", "100vh");

    // Add a group for links and nodes
    const g = svg.append("g");

    // Add zoom behavior
    const zoom = d3.zoom().scaleExtent([0.2, 3]).on("zoom", function (event) {
        g.attr("transform", event.transform);
    });

    svg.call(zoom);

    // Set the initial zoom level to 0.2
    svg.call(zoom.transform, d3.zoomIdentity.scale(0.2));

    // Define marker for arrowheads
    svg.append("defs")
        .append("marker")
        .attr("id", "arrowhead")
        .attr("viewBox", "-0 -5 10 10")
        .attr("refX", 23)
        .attr("refY", 0)
        .attr("orient", "auto")
        .attr("markerWidth", 6)
        .attr("markerHeight", 6)
        .append("path")
        .attr("d", "M 0,-5 L 10 ,0 L 0,5")
        .attr("fill", "#EFEFEF");

    // Create force simulation
    const simulation = d3
        .forceSimulation(props.nodes)
        .force("link", d3.forceLink(props.links).id((d) => d.id).distance(100))
        .force("charge", d3.forceManyBody().strength(-300))
        .force("center", d3.forceCenter(width / 2 / 0.2, height / 2 / 0.2));

    // Add links
    const link = g
        .append("g")
        .selectAll("line")
        .data(props.links)
        .enter()
        .append("line")
        .attr("stroke-width", 5)
        .attr("stroke", "#EFEFEF")
        .attr("fill", "#EFEFEF")
        .attr("marker-end", "url(#arrowhead)");

    // Add nodes with tooltip
    const node = g
        .append("g")
        .selectAll("circle")
        .data(props.nodes)
        .enter()
        .append("circle")
        .attr("r", (d) => {
            if (d.id === "100") {
                return 30;
            } else {
                return 20;
            }
        })
        .attr("fill", (d) => {
            if (d.id.startsWith('100')) {
                return 'red';
            } else if (d.id.startsWith('1')) {
                return 'blue';
            } else if (d.id.startsWith('2')) {
                return 'green';
            } else if (d.id.startsWith('3')) {
                return 'orange';
            } else {
                return '#69b3a2';
            }
        })
        .on("mouseover", handleMouseOver)
        .on("mouseout", handleMouseOut)
        .call(
            d3
                .drag()
                .on("start", function (event, d) {
                    if (!event.active) simulation.alphaTarget(0.3).restart();
                    d.fx = d.x;
                    d.fy = d.y;
                })
                .on("drag", function (event, d) {
                    d.fx = event.x;
                    d.fy = event.y;
                })
                .on("end", function (event, d) {
                    if (!event.active) simulation.alphaTarget(0);
                    d.fx = null;
                    d.fy = null;
                })
        );

    // Tooltip div
    const tooltip = d3
        .select(graphContainer.value)
        .append("div")
        .style("position", "absolute")
        .style("visibility", "hidden")
        .style("background", "rgba(0, 0, 0, 0.7)")
        .style("color", "white")
        .style("padding", "10px")
        .style("border-radius", "10px")
        .style("pointer-events", "none")
        .style("max-width", "400px");

    // Handle mouse over event to show tooltip
    function handleMouseOver(event, d) {
        const choicesHtml = d.choices ?
            "<br>" +
            d.choices.map((item, i) => `<strong>Answer ${i + 1}:</strong> ${item.text} <strong>&#8594;</strong> ${item.destination_id}`)
                .join("<br>") : '';

        tooltip.style("visibility", "visible")
            .html(`
            <strong>ID:</strong> ${d.id} <br>
            <strong>${d.character}:</strong>
            "${d.content}" <br>
            ${choicesHtml}
        `);
    }

    // Handle mouse out event to hide tooltip
    function handleMouseOut() {
        tooltip.style("visibility", "hidden");
    }

    // Update positions on each simulation tick
    simulation.on("tick", () => {
        link
            .attr("x1", (d) => d.source.x)
            .attr("y1", (d) => d.source.y)
            .attr("x2", (d) => d.target.x)
            .attr("y2", (d) => d.target.y);

        node.attr("cx", (d) => d.x).attr("cy", (d) => d.y);
    });

    // Update tooltip position with mouse movement
    svg.on("mousemove", function (event) {
        tooltip
            .style("top", `${event.clientY + 10}px`)
            .style("left", `${event.clientX + 10}px`);
    });
}

// Run the graph creation when the component is mounted
onMounted(() => {
    createGraph();
});
</script>
